### ISSUE TITLE
Header updates

### ISSUE THREAD

**Issue by camilovegag** [lexicongovernance/forum-frontend#124]
# Overview
Based on the feedback, the header will face the following updates: 
- [x] Change Header to Plural Research Experiment.
- [x] Make subtitle larger.
- [ ] Change logo to a plainer prism.

The `Plural Research Experiment` can be a bit tricky as today, this is implemented with a `display: grid` with burnt measures, same for the subtitle.
### Figma:
<img width="390" alt="Screenshot 2024-02-05 at 9 46 11 AM" src="https://github.com/lexicongovernance/forum-frontend/assets/59750365/2d3348ff-995d-4cc9-8263-1c3b47b65c7f">

The change should be done at `grid-template-columns` and `grid-template-rows`

```css
export const LogoContainer = styled.div`
  display: block;

  @media (min-width: 640px) {
    cursor: pointer;
    column-gap: 1rem;
    display: grid;
    grid-template-columns: 6rem 6.5rem 4rem;
    grid-template-rows: 3.5rem 2rem;
    row-gap: 0.5rem;
  }
`;
```
To make the logo planner, the AI generated image should match the Dark Side of the Moon album cover by Pink Floyd aesthetic.
